name: Ansys Prime Server gRPC API CI

on:
  pull_request:
  push:
    tags:
      - "v*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'
  LIBRARY_NAME: 'ansys-api-meshing-prime'
  LIBRARY_NAMESPACE: 'ansys.api.meshing.prime'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    name: "Build package"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Install the library"
        run: |
          python -m pip install .

      - name: "Test import"
        run: |
          python -c "from ${{ env.LIBRARY_NAMESPACE }} import __version__; print(__version__)"

  build-library:
    name: "Build library"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/build-library@v10
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  release:
    name: Release project
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags') }}
    needs: build-library
    runs-on: ubuntu-latest
    # INFO: Specifying a GitHub environment is optional but encouraged
    environment: release
    # INFO: Trusted publishers require these permissions
    permissions:
      id-token: write
      contents: write
    steps:
  
      - name: "Download the library artifacts from build-library step"
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ${{ env.LIBRARY_NAME }}-artifacts
          path: ${{ env.LIBRARY_NAME }}-artifacts
  
      - name: "Upload artifacts to PyPI using trusted publisher"
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: "https://upload.pypi.org/legacy/"
          print-hash: true
          packages-dir: ${{ env.LIBRARY_NAME }}-artifacts
          skip-existing: false
  
      - name: "Release to GitHub"
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ${{ env.LIBRARY_NAME }}-artifacts/*.whl }}
            ${{ env.LIBRARY_NAME }}-artifacts/*.tar.gz
