name: CI/CD for ansys-api-meshing-prime

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install build requirements
        run: pip install build
      - name: Build api package
        run: |
          python -m build
      - name: Test package
        run: |
          python -m pip install dist/*.whl
          python -c "import ansys.api.meshing.prime; print('Succesfully imported ansys.api.meshing.prime')"
          python -c "from ansys.api.meshing.prime import __version__; print(__version__)"
      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: ansys-api-meshing-prime
          path: dist/
          retention-days: 7
  
  Release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R

      # - name: Upload to Private PyPi
      #   run: |
      #     pip install twine
      #     python -m twine upload --skip-existing ./**/*.whl
      #   env:
      #     TWINE_USERNAME: PAT
      #     TWINE_PASSWORD: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
      #     TWINE_REPOSITORY_URL: https://pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/upload

      # - name: Upload to Public PyPi
      #   run: |
      #     pip install twine
      #     twine upload --skip-existing ./**/*.whl
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     generate_release_notes: true
      #     files: |
      #       ./**/*.whl