name: Ansys Prime Server gRPC API CI

on:
  pull_request:
  push:
    tags:
      - "v*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.10'
  LIBRARY_NAME: 'ansys-api-meshing-prime'
  LIBRARY_NAMESPACE: 'ansys.api.meshing.prime'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    name: "Build package"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

      - name: "Install the library"
        run: |
          python -m pip install .

      - name: "Test import"
        run: |
          python -c "from ${{ env.LIBRARY_NAMESPACE }} import __version__; print(__version__)"

  build-library:
    name: "Build library"
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/build-library@v5
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  release:
    name: "Release library"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build-library
    runs-on: ubuntu-latest
    steps:
      - name: "Release to the public PyPI"
        uses: ansys/actions/release-pypi-public@v5
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.TWINE_TOKEN }}

      - name: "Release to GitHub"
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ${{ env.LIBRARY_NAME }}-artifacts/*.whl }}
            ${{ env.LIBRARY_NAME }}-artifacts/*.tar.gz
